/* eslint-disable */
/* auto-generated by napi-rs */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let loadError = null;

const triples = {
  'darwin-x64': 'sso-jwt.darwin-x64.node',
  'darwin-arm64': 'sso-jwt.darwin-arm64.node',
  'linux-x64-gnu': 'sso-jwt.linux-x64-gnu.node',
  'linux-arm64-gnu': 'sso-jwt.linux-arm64-gnu.node',
  'win32-x64-msvc': 'sso-jwt.win32-x64-msvc.node',
};

function getTriple() {
  if (platform === 'darwin') return `darwin-${arch}`;
  if (platform === 'win32') return `win32-${arch}-msvc`;
  if (platform === 'linux') return `linux-${arch}-gnu`;
  return null;
}

const triple = getTriple();
if (triple && triples[triple]) {
  const localPath = join(__dirname, triples[triple]);
  try {
    if (existsSync(localPath)) {
      nativeBinding = require(localPath);
    } else {
      nativeBinding = require(`sso-jwt-${triple}`);
    }
  } catch (e) {
    loadError = e;
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(
    `Failed to load native binding for ${platform}-${arch}. ` +
      'Run `npm run build` or install the platform-specific package.'
  );
}

module.exports = nativeBinding;
